---
title: "Summary Paper: Effect of Major Historical Events on S&P500 Index"
author: "Bharat Khandelwal, Dinesh Chandra Gaddam, Phanindra Kumar Kalaga, Prudhvi chekuri"
date: "`r Sys.Date()`"
output: 
  prettydoc::html_pretty:
    theme: architect
    toc: yes
---

## 2. Introduction
<span style="font-size: 12px;  text-align: justify;">
<p>
The S&P 500 is a stock market index that measures the performance of 500 large-cap U.S. companies listed on stock exchanges. An index in finance refers to a statistical measure of change in a securities market. It typically represents a portfolio of securities that represent a particular market or sector. Stock market indices are used to track the performance of a specific group of stocks.overall, The index is market-capitalization -weighted, meaning that larger companies have a greater impact on its value. Now, coming to the S&P 500, it includes companies from diverse industries such as technology, healthcare, financial services, consumer discretionary and industries. The S&P 500 is widely regarded as one of the best benchmarks for the performance of the U.S. stock market.
</P>
<P>This project utilizes a dataset from Yahoo finance containing information on over 6,000 instances, with the goal of developing Explanatory Data Analysis to effectively distinguish Data observations for analysis. The dataset includes characteristics such as open, close, High, Volume and Low. Through exploratory data analysis, we will identify trends and correlations between these features and gather insights. Firstly we will see if the dataset needs any changes like pre processing then we will continue with analysis using t-test's. 
</P>
<P>The results produced from this project  can provide valuable insights into market dynamics, risk management, investment strategies, and decision-making, contributing to more informed and successful investing over time.
</P>
</span>






## Smart Question 2   : How is the S&P500 Index affected by the COVID-19 pandemic?
<span style="font-size: 12px;  text-align: justify;">
<p> Covid-19 has several negative and positive effects on the Society and S&P500 as a whole</p>

<p><strong> Positive Effects:</strong></p>
<p>
The COVID-19 outbreak acted as a catalyst, rapidly advancing the shift towards digitalization and remote operations across many sectors. This transition played into the strengths of major technology firms. Companies such as Amazon, Microsoft, Apple, and Google experienced a surge in the demand for their digital offerings and solutions that enabled remote work, online shopping, virtual communication, and digital entertainment. As a result of this heightened demand, the stocks of these tech giants saw substantial price increases. Given their significant weightings in the S&P 500 index, the stock price appreciation of these technology behemoths made a positive contribution to the overall performance of the benchmark index.</p>

<p>To mitigate the economic impacts of the lockdowns imposed due to the pandemic, central banks like the Federal Reserve and governments across the globe injected substantial amounts of capital and enacted stimulus programs. This massive influx of liquidity into the financial system helped stabilize and calm the markets during a period of heightened volatility and uncertainty. Moreover, these interventions bolstered investor sentiment and confidence in the markets' resilience. Consequently, this renewed optimism among investors, fueled by the stimulus measures, had a favorable effect on the performance of the S&P 500 index. similarly these helped in growth of healthcare growth</p>


<p><strong>Negative Effects:</strong> </p>
<p>Firstly, Industries such as travel, hospitality, and retail were severely affected by lockdowns and reduced consumer spending. Companies in these sectors experienced significant stock price declines, dragging down the overall performance of the S&P 500.</p>  
<p>The pandemic caused extreme volatility in financial markets. Uncertainty about the virus's impact on the economy led to sharp market swings, causing fluctuations in the S&P 500 and increasing investor anxiety.</p>


<p><b>Null Hypothesis</b> : There is no significant difference between the S&P 500 Index before and after the Covid-19.</p>

<p><b>Alternate Hypothesis</b> : There is a significant difference between the S&P 500 Index before and after the Covid-19.</p>


<p>------------------------------------------------------------------------------------------------------------</p>
<p><b>Welch Two Sample t-test</b></p>
```{r, include=T,echo=FALSE, results=T}
df <- data.frame(read.csv('../dataset2003-2023.csv'))
df$Date <- as.Date(df$Date)
new_df <- subset(df, select = -c(6))
num_variables <- subset(new_df,select = -c(1))
new_df$daily_change <- (new_df$Close / lag(new_df$Close) - 1) * 100
new_df2 <- na.omit(new_df)

new_before_covid <- subset(new_df2, Date <= '2019-12-31'  & Date >= '2016-06-01')
new_after_covid <- subset(new_df2, Date < '2023-05-11'  & Date >= '2020-01-01')

t_test_covid = t.test(new_before_covid$Close, new_after_covid$Close, na.rm= TRUE)
t_test_covid
```

<p>------------------------------------------------------------------------------------------------------------</p>

<p><b>Observation:</b> </p>

<p>By comparing and performing analysis using t-test. we have found that the mean of close instance before covid and after covid is not as expected. the mean of close is higher after the covid by 1266 compared to before covid. Furthermore the p-value is less than 2e-16 which means we reject null hypothesis. After reading an article from Wall street journal we have come to know that covid effects were reduced and recovered within just 119 days which is very less compared to Great recession as the government got involved and helped the stock market recover faster than expected.</p>

</span>