---
title: "Effect of Major Historical Events on S&P500 Index"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r init, include=FALSE}
# Load all required packages
library(dplyr)
library(ggplot2)
library(ezids)
library(lubridate)
library(corrplot)
knitr::opts_chunk$set(warning = F, results = "markup", message = F)
options(scientific=T, digits = 3) 
```



# Team Neo Midterm Project

Terminology in Trading

+ "open" - The opening price for the specified date(s).
+ "close" - The closing price for the specified date(s).
+ "high" - The high price for the specified date(s).
+ "low" - The low price for the specified date(s).
+ "volume" - The volume for the specified date(s).
+ "change" - The price change since the previous trading weekly close.
             (For monthly take previous trading month’s close and for daily take previous
             trading day’s close.)


We are analyzing how major historical events impacted the S&P 500 index using daily data in last 20 years, that is from 2003-2023. Specifically, we will:

1. Examine the daily closing prices of the index to see how events affected the price levels.

2. Calculate and analyze the daily returns and standardized daily returns to understand volatility around events. 

3. Study the correlation between different variables in the dataset to identify relationships.

4. Plot the daily returns, standardized returns, and closing prices around major events to visualize the impacts.

5. Remove outliers from the data and re-analyze to ensure robustness of our findings.

By looking at prices, returns, correlations, visualizations, and handling outliers, we aim to comprehensively assess how significant historical occurrences influenced the behavior of the S&P 500 index over this 20-year period.


